version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name mylambdafunction-dev --zip-file fileb://deployment_package.zip
      - chmod +x test.sh
      - ./test.sh
      - aws lambda publish-version  --function-name mylambdafunction-dev
      - echo "Printing Latest Version of Lambda Fcution"
      - eval LATEST_VERSION=$(aws lambda list-versions-by-function --function-name mylambdafunction-dev --query "max_by(Versions, &Version).{Version:Version}" --output text)
      - echo "Updating Latest Version to alias "
      - aws lambda update-alias --function-name mylambdafunction-dev --name Production --function-version $LATEST_VERSION
      - echo "DONE!!"
